### ISSUE TITLE
haml-lint version

### ISSUE THREAD

**Issue by patfrat** [prontolabs/pronto-haml#1]
Hello,

haml-lint is now at version 0.7.0 but pronto-haml require 'haml-lint', '~> 0.6.0', '>= 0.6.0'
Is it possible to remove  '~> 0.6.0' from pronto-haml.gemspec to get the latest version of haml-lint working ?
What is the problem with the newer version of haml-lint ?

**Comment by jhass** [comment]
Ping, it got outdated again. A less strict requirement or at least a quick check if the tests still pass with each `haml_lint` release would be nice. [Here's an RSS feed of haml_lint releases](https://rubygems.org/gems/haml_lint/versions.atom)

**Comment by mmozuras** [comment]
@jhass updated and released as [v0.4.4](https://github.com/mmozuras/pronto-haml/releases/tag/v0.4.4).

I'm in progress of creating integration specs for `pronto-` runners. `pronto-haml` doesn't have those yet, so I do a quick manual check instead. Terrible, I know :smile: 

As the API `pronto-haml` uses is not officially meant to be used like this, I can't depend on it not breaking. I've been burned by having a less strict requirement with another runner. Of course, I'd listen to an argument to change my ways :smile:

**Comment by jhass** [comment]
Thanks. I guess some integration tests are the way to go then.

**Comment by doits** [comment]
Outdated again - I see you commited the update but didn't release it to rubygems yet. Can you release the new version or is anything broken?

**Comment by mmozuras** [comment]
@doits done, released :bow:
