### ISSUE TITLE
Not catching syntax errors

### ISSUE THREAD

**Issue by giedriusr** [prontolabs/pronto-haml#7]
Hey,

We are using pronto to run rubocop, haml on our PRs. What we have recently noticed that pronto-haml didn't catch syntax error exception while pure haml-lint did.

We executed `rubocop -a` on multiple files and few haml files were updated with the following:

```diff
-#modal-window.modal.fade{"aria-hidden" => "true", "data-backdrop" => "static", "aria-labelledby" => "myModalLabel", "role" => "dialog"}
+# modal-window.modal.fade{"aria-hidden" => "true", "data-backdrop" => "static", "aria-labelledby" => "myModalLabel", "role" => "dialog"}
```

It's an obvious syntax error from haml.

```
$ git show --name-only | grep 'haml' | xargs haml-lint
_edit_page_block_modal.html.haml:0 [E] Syntax: Illegal element: classes and ids must have values.
_edit_cart_item_modal.html.haml:0 [E] Syntax: Illegal element: classes and ids must have values.

2 files inspected, 2 lints detected
```

But `pronto run` did not catch those syntax issues. A bug or some configuration issue?

Thanks!

**Comment by mknapik** [comment]
What was the command exit status?
Did you manage to figure out what was the issue?

**Comment by giedriusr** [comment]
I did not spend time investigating, was interested if anyone else had similar experience. It had some time ago, but I believe the issue is still relevant.

**Comment by mknapik** [comment]
Would you be willing to create minimal gist which replicates the issue?

**Comment by ashkulz** [comment]
@giedriusr please reopen the issue if you can create a reproducible test case.
